title: SocialMediaIE - Social Media Information Extraction
description: Tools for efficient social media information extraction using advanced machine learning techniques
#github:
#  project_title: Hands on advanced machine learning for information extraction from tweets tasks, data, and open source tools
#  project_tagline: To be presented at ACM HYPERTEXT 2019
google_analytics: UA-44393164-1  
theme: jekyll-theme-cayman
